// cars-data.js — BILHK
// Central brand/model list used by sell.html, edit-car.html, filter.html, app.js and results.html.
// The list is intentionally broad. Users can still type a custom model if it is not listed.

export const carData = {
  "Abarth": ["500", "595", "695", "124 Spider"],
  "Acura": ["ILX", "TLX", "RLX", "Integra", "MDX", "RDX", "NSX"],
  "Aiways": ["U5", "U6"],
  "Alfa Romeo": ["Giulia", "Giulietta", "MiTo", "Stelvio", "Tonale", "4C"],
  "Alpine": ["A110"],
  "Aston Martin": ["DB9", "DB11", "DB12", "DBS", "Vantage", "Vanquish", "Rapide", "DBX"],
  "Audi": ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "TT", "R8", "e-tron", "e-tron GT", "RS3", "RS4", "RS5", "RS6", "RS7"],
  "BAIC": ["X25", "X35", "X55", "BJ40"],
  "Bentley": ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne"],
  "BMW": ["1-serie", "2-serie", "3-serie", "4-serie", "5-serie", "6-serie", "7-serie", "8-serie", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z3", "Z4", "i3", "i4", "i5", "i7", "i8", "iX", "M2", "M3", "M4", "M5"],
  "BYD": ["Atto 3", "Dolphin", "Seal", "Seal U", "Tang", "Han"],
  "Cadillac": ["ATS", "CTS", "CT4", "CT5", "CT6", "Escalade", "XT4", "XT5", "XT6", "Lyriq"],
  "Changan": ["CS35", "CS55", "CS75", "UNI-K", "UNI-T"],
  "Chery": ["Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8", "Arrizo 5"],
  "Chevrolet": ["Aveo", "Spark", "Cruze", "Malibu", "Impala", "Camaro", "Corvette", "Trax", "Captiva", "Equinox", "Tahoe", "Suburban", "Silverado"],
  "Chrysler": ["300C", "Sebring", "Voyager", "Pacifica", "PT Cruiser"],
  "Citroën": ["C1", "C2", "C3", "C3 Aircross", "C4", "C4 Cactus", "C5", "C5 Aircross", "Berlingo", "Jumpy", "Spacetourer"],
  "Cupra": ["Born", "Formentor", "Leon", "Ateca", "Tavascan"],
  "Dacia": ["Sandero", "Logan", "Duster", "Jogger", "Spring", "Lodgy"],
  "Daewoo": ["Matiz", "Lanos", "Nubira", "Leganza"],
  "Daihatsu": ["Charade", "Cuore", "Sirion", "Terios", "Materia"],
  "Dodge": ["Charger", "Challenger", "Durango", "Journey", "Ram", "Caliber", "Nitro"],
  "DS": ["DS 3", "DS 4", "DS 5", "DS 7", "DS 9"],
  "Ferrari": ["458", "488", "F8", "Roma", "Portofino", "California", "812", "SF90", "Purosangue"],
  "Fiat": ["500", "500X", "500L", "Panda", "Punto", "Tipo", "Bravo", "Doblo", "Ducato", "Fullback"],
  "Ford": ["Ka", "Fiesta", "Focus", "Mondeo", "Fusion", "Mustang", "Puma", "Kuga", "Edge", "Explorer", "Ranger", "Transit", "S-Max", "Galaxy"],
  "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  "GMC": ["Terrain", "Acadia", "Yukon", "Sierra", "Canyon", "Hummer EV"],
  "Great Wall": ["Wingle", "Poer", "Haval H2", "Haval H6", "Haval Jolion"],
  "Honda": ["Jazz", "Civic", "Accord", "Insight", "CR-Z", "HR-V", "CR-V", "ZR-V", "Pilot", "e", "NSX"],
  "Hongqi": ["E-HS9", "H5", "H9", "HS5", "HS7"],
  "Hummer": ["H1", "H2", "H3", "EV"],
  "Hyundai": ["i10", "i20", "i30", "i40", "Elantra", "Sonata", "Kona", "Tucson", "Santa Fe", "Bayon", "IONIQ", "IONIQ 5", "IONIQ 6", "Nexo"],
  "Infiniti": ["Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX60", "QX70", "QX80"],
  "Isuzu": ["D-Max", "MU-X"],
  "Iveco": ["Daily"],
  "Jaguar": ["XE", "XF", "XJ", "F-Type", "E-Pace", "F-Pace", "I-Pace"],
  "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Gladiator", "Avenger"],
  "Kia": ["Picanto", "Rio", "Ceed", "ProCeed", "Optima", "Stinger", "Stonic", "Niro", "Sportage", "Sorento", "EV3", "EV6", "EV9", "Soul"],
  "Koenigsegg": ["Agera", "Regera", "Jesko", "Gemera"],
  "Lada": ["Niva", "Vesta", "Granta"],
  "Lamborghini": ["Gallardo", "Huracán", "Aventador", "Urus", "Revuelto"],
  "Lancia": ["Ypsilon", "Delta", "Thema", "Voyager"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque", "Freelander"],
  "Lexus": ["CT", "IS", "ES", "GS", "LS", "UX", "NX", "RX", "RZ", "GX", "LX", "LC", "RC"],
  "Lincoln": ["MKZ", "Continental", "Corsair", "Nautilus", "Aviator", "Navigator"],
  "Lotus": ["Elise", "Exige", "Evora", "Emira", "Eletre", "Emeya"],
  "Lucid": ["Air", "Gravity"],
  "Maserati": ["Ghibli", "Quattroporte", "GranTurismo", "Levante", "Grecale", "MC20"],
  "Mazda": ["2", "3", "5", "6", "CX-3", "CX-30", "CX-5", "CX-60", "CX-80", "MX-5", "MX-30", "RX-8"],
  "McLaren": ["540C", "570S", "600LT", "650S", "720S", "750S", "Artura", "GT", "P1"],
  "Mercedes-Benz": ["A-Klass", "B-Klass", "C-Klass", "E-Klass", "S-Klass", "CLA", "CLS", "SL", "SLC", "GLA", "GLB", "GLC", "GLE", "GLS", "G-Klass", "V-Klass", "EQB", "EQA", "EQC", "EQE", "EQS", "AMG GT", "Sprinter", "Vito"],
  "MG": ["3", "4", "5", "ZS", "HS", "Marvel R", "Cyberster"],
  "Mini": ["Cooper", "Cooper S", "Clubman", "Countryman", "Paceman", "Cabrio"],
  "Mitsubishi": ["Colt", "Lancer", "Space Star", "ASX", "Eclipse Cross", "Outlander", "Pajero", "L200"],
  "NIO": ["ET5", "ET7", "EL6", "EL7", "EL8", "ES8"],
  "Nissan": ["Micra", "Note", "Juke", "Qashqai", "X-Trail", "Ariya", "Leaf", "Navara", "GT-R", "370Z", "350Z"],
  "Opel": ["Adam", "Corsa", "Astra", "Insignia", "Mokka", "Crossland", "Grandland", "Zafira", "Vivaro", "Combo"],
  "Peugeot": ["108", "208", "308", "508", "2008", "3008", "5008", "Rifter", "Traveller", "Partner"],
  "Polestar": ["1", "2", "3", "4"],
  "Porsche": ["718 Boxster", "718 Cayman", "911", "Panamera", "Macan", "Cayenne", "Taycan"],
  "RAM": ["1500", "2500", "3500"],
  "Renault": ["Clio", "Megane", "Scenic", "Captur", "Kadjar", "Koleos", "Talisman", "Zoe", "Austral", "Espace", "Kangoo", "Trafic"],
  "Rivian": ["R1T", "R1S"],
  "Rolls-Royce": ["Ghost", "Phantom", "Wraith", "Dawn", "Cullinan", "Spectre"],
  "Rover": ["25", "45", "75"],
  "Saab": ["9-3", "9-5", "900", "9000", "96"],
  "Seat": ["Mii", "Ibiza", "Leon", "Toledo", "Arona", "Ateca", "Tarraco", "Alhambra"],
  "Skoda": ["Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq", "Roomster", "Yeti"],
  "Smart": ["ForTwo", "ForFour", "#1", "#3"],
  "SsangYong": ["Tivoli", "Korando", "Rexton", "Musso"],
  "Subaru": ["Impreza", "Legacy", "Outback", "Forester", "XV", "BRZ", "WRX", "Solterra"],
  "Suzuki": ["Alto", "Swift", "Baleno", "Ignis", "Vitara", "S-Cross", "Jimny", "Across", "Swace"],
  "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],
  "Toyota": ["Aygo", "Yaris", "Corolla", "Auris", "Avensis", "Camry", "Prius", "C-HR", "RAV4", "Highlander", "Land Cruiser", "Hilux", "Proace", "bZ4X", "Supra", "GT86"],
  "Volkswagen": ["Up", "Polo", "Golf", "Jetta", "Passat", "Arteon", "Beetle", "T-Cross", "T-Roc", "Tiguan", "Touareg", "Touran", "Sharan", "Caddy", "Transporter", "ID.3", "ID.4", "ID.5", "ID.7", "Amarok"],
  "Volvo": ["C30", "C40", "S40", "S60", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40", "XC60", "XC70", "XC90", "EX30", "EX40", "EX90"],
  "XPeng": ["G3", "G6", "G9", "P5", "P7"],
  "Zeekr": ["001", "007", "X"],
  "Annat märke": ["Annan modell"]
};

export const brands = Object.keys(carData).sort((a, b) => a.localeCompare(b, 'sv'));

export const featuresList = [
  "ABS-bromsar", "ACC", "Adaptiv farthållare", "Autobroms", "Filassistans", "Döda vinkel-varnare",
  "360° Kamera", "Backkamera", "Parkeringssensorer", "Navigation", "Apple CarPlay", "Android Auto",
  "Bluetooth", "Head-up display", "Matrix LED", "LED-strålkastare", "Xenonljus", "Dragkrok",
  "Panoramaglastak", "Taklucka", "Skinnklädsel", "Alcantara", "Elstolar", "Minnesstolar",
  "Sätesvärme fram", "Sätesvärme bak", "Rattvärme", "Ventilerade säten", "Keyless", "Elbaklucka",
  "Fyrhjulsdrift", "Sportpaket", "M-sport", "AMG-paket", "S-line", "Full servicehistorik",
  "Nybesiktigad", "Vinterdäck", "Sommardäck", "Garanti", "Leasing möjlig", "Momsbil"
];
